### ISSUE TITLE
`avoid-reverse` is wrong

### ISSUE THREAD

**Issue by fregante** [freaktechnik/eslint-plugin-array-func#68]
Readme example:

```js
const sum = array.reverse().reduce((p, c) => p + c, 0);
const reverseSum = array.reverse().reduceRight((p, c) => p + c, 0);
```

The sums are a bad example since their order doesn't matter. Try this:

```js
['a','b','c'].reverse().reduce((p, c) => p + c, '');
// 'cba'
['a','b','c'].reverse().reduceRight((p, c) => p + c, '');
// 'abc'
```
```js
['a','b','c'].reduce((p, c) => p + c, '');
// 'abc'
['a','b','c'].reduceRight((p, c) => p + c, '');
// 'cba'
```

Did you mean to replace `.reverse().reduce()` with `.reduceRight()` and vice-versa instead?

**Comment by freaktechnik** [comment]
I will admit that the readme examples aren't always great in showing the full behavior, their main intent is to show the syntax that triggers a rule, since the rules do not do any behavioral analysis of the callback.

The rule does indeed suggest to use `reduceRight` instead of `reverse().reduce()` and `reduce` instead of `reverse().reduceRight()`.
